global class AhaErlFlowOutputLine {
    @AuraEnabled public String outputReference { get; set; }
    @AuraEnabled public String sorUnit { get; set; }
    @AuraEnabled public String sorTrade { get; set; }
    @AuraEnabled public String sorCode { get; set; }
    @AuraEnabled public String sorSubject { get; set; }
    @AuraEnabled public String sorDescription { get; set; }
    @AuraEnabled public String sorQuantity { get; set; }
    @AuraEnabled public String sorPriority { get; set; }
    @AuraEnabled public String sorJobTitle { get; set; }
    @AuraEnabled public String sorHeading { get; set; }
    @AuraEnabled public String sorComment { get; set; }
    @AuraEnabled public String sorRate { get; set; }
    @AuraEnabled public String repairLocation { get; set; }
}
